extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_f3dlite_material_002_lights;
extern Lights1 wf_dl_f3dlite_material_003_lights;
extern Lights1 wf_dl_f3dlite_material_lights;
extern Lights1 wf_dl_f3dlite_material_004_lights;
extern u8 wf_dl_wf_textures_02800_rgba16_rgba16[];
extern u8 wf_dl_wf_textures_02000_rgba16_rgba16[];
extern u8 wf_dl_wf_textures_05800_rgba16_ci8[];
extern u8 wf_dl_wf_textures_05800_rgba16_pal_rgba16[];
extern u8 wf_dl_gnarp_rgba16[];
extern Vtx wf_dl_Cylinder_001_mesh_layer_1_vtx_0[537];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_001_mesh_layer_1_vtx_1[237];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cylinder_002_mesh_layer_1_vtx_0[454];
extern Gfx wf_dl_Cylinder_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_002_mesh_layer_1_vtx_1[1059];
extern Gfx wf_dl_Cylinder_002_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cylinder_002_mesh_layer_1_vtx_2[16];
extern Gfx wf_dl_Cylinder_002_mesh_layer_1_tri_2[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_revert_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx mat_revert_wf_dl_f3dlite_material_002[];
extern Gfx mat_wf_dl_f3dlite_material_003[];
extern Gfx mat_revert_wf_dl_f3dlite_material_003[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_revert_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_f3dlite_material_004[];
extern Gfx mat_revert_wf_dl_f3dlite_material_004[];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_002_mesh_layer_1[];
