extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_Grass_Example_001_lights;
extern Lights1 castle_inside_dl_Grass_Example_lights;
extern Vtx castle_inside_dl_Cube_mesh_layer_1_vtx_0[76];
extern Gfx castle_inside_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cylinder_mesh_layer_1_vtx_0[32];
extern Gfx castle_inside_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cylinder_001_mesh_layer_1_vtx_0[32];
extern Gfx castle_inside_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cylinder_002_mesh_layer_1_vtx_0[32];
extern Gfx castle_inside_dl_Cylinder_002_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cylinder_003_mesh_layer_1_vtx_0[32];
extern Gfx castle_inside_dl_Cylinder_003_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Level_Mesh_mesh_layer_1_vtx_0[145];
extern Gfx castle_inside_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Gfx mat_castle_inside_dl_Grass_Example_001[];
extern Gfx mat_revert_castle_inside_dl_Grass_Example_001[];
extern Gfx mat_castle_inside_dl_Grass_Example[];
extern Gfx mat_revert_castle_inside_dl_Grass_Example[];
extern Gfx castle_inside_dl_Cube_mesh_layer_1[];
extern Gfx castle_inside_dl_Cylinder_mesh_layer_1[];
extern Gfx castle_inside_dl_Cylinder_001_mesh_layer_1[];
extern Gfx castle_inside_dl_Cylinder_002_mesh_layer_1[];
extern Gfx castle_inside_dl_Cylinder_003_mesh_layer_1[];
extern Gfx castle_inside_dl_Level_Mesh_mesh_layer_1[];
